"""trying migrations

Revision ID: 019d28703804
Revises: 
Create Date: 2025-03-31 22:27:32.578380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel          # Added


# revision identifiers, used by Alembic.
revision: str = '019d28703804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
