"""one more

Revision ID: 6fa8b761f89b
Revises: 13d7296e17ad
Create Date: 2025-03-31 23:10:52.028528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel          # Added


# revision identifiers, used by Alembic.
revision: str = '6fa8b761f89b'
down_revision: Union[str, None] = '13d7296e17ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('desc2', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'desc2')
    # ### end Alembic commands ###
