"""remove desc2 from Item

Revision ID: ba4034a8012b
Revises: 019d28703804
Create Date: 2025-03-31 23:05:36.344480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel          # Added


# revision identifiers, used by Alembic.
revision: str = 'ba4034a8012b'
down_revision: Union[str, None] = '019d28703804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand')
    op.drop_table('cover')
    op.drop_table('image')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=200), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('cover_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_id'], ['cover.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
