"""remove disc2 from Item

Revision ID: bb801a2dcc8b
Revises: 6fa8b761f89b
Create Date: 2025-03-31 23:14:30.808086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel          # Added


# revision identifiers, used by Alembic.
revision: str = 'bb801a2dcc8b'
down_revision: Union[str, None] = '6fa8b761f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'desc2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('desc2', sa.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
