"""remove desc2 from Item

Revision ID: f552f257d040
Revises: f60a8df87671
Create Date: 2025-04-01 00:59:31.705691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel          # Added


# revision identifiers, used by Alembic.
revision: str = 'f552f257d040'
down_revision: Union[str, None] = 'f60a8df87671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'desc2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('desc2', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
